name: Run main.py and commit changes

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 5 minutes

jobs:
  run-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This grants write permissions to the GITHUB_TOKEN

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the token with write permissions

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python main.py  # Ensure this script outputs pta_nhi.json

      - name: Commit and push changes if there are any
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pta_nhi.json
          git diff --staged --quiet || (git commit -m 'Update pta_nhi.json' && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
